# dev testing deployment - ensure you are at root of git repo.
# deployment linux:     docker compose -p evecelery-dev -f ./dev/stacks/standard.yaml up -d --pull always

version: '3.8'
services:
  rabbitmq:
    image: docker.io/library/rabbitmq:3-management
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 2048M
    hostname: insightmq
    environment:
      RABBITMQ_DEFAULT_USER: "evecelery"
      RABBITMQ_DEFAULT_PASS: "evecelery"
      RABBITMQ_DEFAULT_VHOST: "evecelery"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - insightdev
    ports:
      - target: 5672
        published: 5672
        protocol: tcp
        mode: host
      - target: 15672
        published: 8080
        protocol: tcp
        mode: host
  redis:
    image: docker.io/library/redis:6
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - redis-data:/data
    networks:
      - insightdev
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    command: --requirepass "evecelery" --appendonly yes --appendfsync everysec
networks:
  insightdev:
volumes:
  db-data:
  rabbitmq-data:
  redis-data:
